Set up diagnostic animations delivery

diff --git a/Pico/do_install b/Pico/do_install
--- a/Pico/do_install
+++ b/Pico/do_install
@@ -1,4 +1,4 @@
-#!/bin/bash -f
+#!/bin/bash
 #set echo
 
 function usage() {
@@ -87,8 +87,6 @@ ${rshell} --quiet cp lib/servo.py \
           lib/tabledefs \
           lib/helpers.py \
           lib/maestro.py \
-          lib/upath.py \
-          lib/ustat.py \
           /pyboard/lib
 echo Installing main.py
 ${rshell} --quiet cp main.py /pyboard
@@ -97,8 +95,8 @@ echo ''
 echo ''
 echo -n 'Install demo/diagnostic animations (y/N):'
 read reply
+echo ''
 if [ $reply = 'y' ] || [ $reply = 'Y' ]; then
-    echo ''
     ${rshell} --quiet cp anims/* /pyboard/anims
 fi
 
@@ -112,9 +110,9 @@ ${rshell} --quiet cp boot.py /pyboard
 # Make the link to commlib in the root directory
 rm -f ../src/commlib.py ../commlib.py
 if [ -d ../src ]; then
-    ln -s commlib.py ../src/commlib.py
+    ln -s ${PWD}/commlib.py ../src/commlib.py
 else
-    ln -s commlib.py ../commlib.py
+    ln -s ${PWD}/commlib.py ../commlib.py
 fi
 if [ -d ../_internal ]; then
     rm -f _internal
@@ -143,7 +141,22 @@ fi
 
 CODE=$?
 if [ $CODE -eq 0 ]; then
-    echo All files validate
+    echo All python files validate
 fi
+
+# Validate installed diagnostic animations
+#if [ $reply = 'y' ] || [ $reply = 'Y' ]; then
+    echo ''
+    # Fails for the .wav files FIXME
+    if [ -f ./verifyload ]; then
+        ./verifyload -p $port -fl `ls anims/*.csv`
+    else
+        python3 verifyload.py -p $port -fl `ls anims/*.csv`
+    fi
+    CODE=$?
+    if [ $CODE -eq 0 ]; then
+        echo Diagnostic anim files validate
+    fi
+#fi
 
 exit
